/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystemeSolaireRouteImport } from './routes/systeme-solaire'
import { Route as MarsRouteImport } from './routes/mars'
import { Route as IndexRouteImport } from './routes/index'

const SystemeSolaireRoute = SystemeSolaireRouteImport.update({
  id: '/systeme-solaire',
  path: '/systeme-solaire',
  getParentRoute: () => rootRouteImport,
} as any)
const MarsRoute = MarsRouteImport.update({
  id: '/mars',
  path: '/mars',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mars': typeof MarsRoute
  '/systeme-solaire': typeof SystemeSolaireRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mars': typeof MarsRoute
  '/systeme-solaire': typeof SystemeSolaireRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mars': typeof MarsRoute
  '/systeme-solaire': typeof SystemeSolaireRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mars' | '/systeme-solaire'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mars' | '/systeme-solaire'
  id: '__root__' | '/' | '/mars' | '/systeme-solaire'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarsRoute: typeof MarsRoute
  SystemeSolaireRoute: typeof SystemeSolaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systeme-solaire': {
      id: '/systeme-solaire'
      path: '/systeme-solaire'
      fullPath: '/systeme-solaire'
      preLoaderRoute: typeof SystemeSolaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mars': {
      id: '/mars'
      path: '/mars'
      fullPath: '/mars'
      preLoaderRoute: typeof MarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarsRoute: MarsRoute,
  SystemeSolaireRoute: SystemeSolaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
