/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro/index'
import { Route as HousingIndexRouteImport } from './routes/housing/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProGliRouteImport } from './routes/pro/gli'
import { Route as ProsinistresSinistresRouteRouteImport } from './routes/pro/(sinistres)/sinistres.route'
import { Route as ProsinistresSinistresIndexRouteImport } from './routes/pro/(sinistres)/sinistres.index'
import { Route as ProsinistresSinistresClaimIdRouteImport } from './routes/pro/(sinistres)/sinistres.$claimId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingIndexRoute = HousingIndexRouteImport.update({
  id: '/housing/',
  path: '/housing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProGliRoute = ProGliRouteImport.update({
  id: '/pro/gli',
  path: '/pro/gli',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsinistresSinistresRouteRoute =
  ProsinistresSinistresRouteRouteImport.update({
    id: '/pro/(sinistres)/sinistres',
    path: '/pro/sinistres',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProsinistresSinistresIndexRoute =
  ProsinistresSinistresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProsinistresSinistresRouteRoute,
  } as any)
const ProsinistresSinistresClaimIdRoute =
  ProsinistresSinistresClaimIdRouteImport.update({
    id: '/$claimId',
    path: '/$claimId',
    getParentRoute: () => ProsinistresSinistresRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pro/gli': typeof ProGliRoute
  '/admin': typeof AdminIndexRoute
  '/housing': typeof HousingIndexRoute
  '/pro': typeof ProIndexRoute
  '/pro/sinistres': typeof ProsinistresSinistresRouteRouteWithChildren
  '/pro/sinistres/$claimId': typeof ProsinistresSinistresClaimIdRoute
  '/pro/sinistres/': typeof ProsinistresSinistresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pro/gli': typeof ProGliRoute
  '/admin': typeof AdminIndexRoute
  '/housing': typeof HousingIndexRoute
  '/pro': typeof ProIndexRoute
  '/pro/sinistres/$claimId': typeof ProsinistresSinistresClaimIdRoute
  '/pro/sinistres': typeof ProsinistresSinistresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pro/gli': typeof ProGliRoute
  '/admin/': typeof AdminIndexRoute
  '/housing/': typeof HousingIndexRoute
  '/pro/': typeof ProIndexRoute
  '/pro/(sinistres)/sinistres': typeof ProsinistresSinistresRouteRouteWithChildren
  '/pro/(sinistres)/sinistres/$claimId': typeof ProsinistresSinistresClaimIdRoute
  '/pro/(sinistres)/sinistres/': typeof ProsinistresSinistresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pro/gli'
    | '/admin'
    | '/housing'
    | '/pro'
    | '/pro/sinistres'
    | '/pro/sinistres/$claimId'
    | '/pro/sinistres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pro/gli'
    | '/admin'
    | '/housing'
    | '/pro'
    | '/pro/sinistres/$claimId'
    | '/pro/sinistres'
  id:
    | '__root__'
    | '/'
    | '/pro/gli'
    | '/admin/'
    | '/housing/'
    | '/pro/'
    | '/pro/(sinistres)/sinistres'
    | '/pro/(sinistres)/sinistres/$claimId'
    | '/pro/(sinistres)/sinistres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProGliRoute: typeof ProGliRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HousingIndexRoute: typeof HousingIndexRoute
  ProIndexRoute: typeof ProIndexRoute
  ProsinistresSinistresRouteRoute: typeof ProsinistresSinistresRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/': {
      id: '/housing/'
      path: '/housing'
      fullPath: '/housing'
      preLoaderRoute: typeof HousingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/gli': {
      id: '/pro/gli'
      path: '/pro/gli'
      fullPath: '/pro/gli'
      preLoaderRoute: typeof ProGliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/(sinistres)/sinistres': {
      id: '/pro/(sinistres)/sinistres'
      path: '/pro/sinistres'
      fullPath: '/pro/sinistres'
      preLoaderRoute: typeof ProsinistresSinistresRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/(sinistres)/sinistres/': {
      id: '/pro/(sinistres)/sinistres/'
      path: '/'
      fullPath: '/pro/sinistres/'
      preLoaderRoute: typeof ProsinistresSinistresIndexRouteImport
      parentRoute: typeof ProsinistresSinistresRouteRoute
    }
    '/pro/(sinistres)/sinistres/$claimId': {
      id: '/pro/(sinistres)/sinistres/$claimId'
      path: '/$claimId'
      fullPath: '/pro/sinistres/$claimId'
      preLoaderRoute: typeof ProsinistresSinistresClaimIdRouteImport
      parentRoute: typeof ProsinistresSinistresRouteRoute
    }
  }
}

interface ProsinistresSinistresRouteRouteChildren {
  ProsinistresSinistresClaimIdRoute: typeof ProsinistresSinistresClaimIdRoute
  ProsinistresSinistresIndexRoute: typeof ProsinistresSinistresIndexRoute
}

const ProsinistresSinistresRouteRouteChildren: ProsinistresSinistresRouteRouteChildren =
  {
    ProsinistresSinistresClaimIdRoute: ProsinistresSinistresClaimIdRoute,
    ProsinistresSinistresIndexRoute: ProsinistresSinistresIndexRoute,
  }

const ProsinistresSinistresRouteRouteWithChildren =
  ProsinistresSinistresRouteRoute._addFileChildren(
    ProsinistresSinistresRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProGliRoute: ProGliRoute,
  AdminIndexRoute: AdminIndexRoute,
  HousingIndexRoute: HousingIndexRoute,
  ProIndexRoute: ProIndexRoute,
  ProsinistresSinistresRouteRoute: ProsinistresSinistresRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
