/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SinistresRouteImport } from './routes/sinistres'
import { Route as IndexRouteImport } from './routes/index'

const SinistresRoute = SinistresRouteImport.update({
  id: '/sinistres',
  path: '/sinistres',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sinistres': typeof SinistresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sinistres': typeof SinistresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sinistres': typeof SinistresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sinistres'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sinistres'
  id: '__root__' | '/' | '/sinistres'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SinistresRoute: typeof SinistresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sinistres': {
      id: '/sinistres'
      path: '/sinistres'
      fullPath: '/sinistres'
      preLoaderRoute: typeof SinistresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SinistresRoute: SinistresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
